### ISSUE TITLE
copyCode.js error in line: const code = codeBlocks[index].innerText;

### ISSUE THREAD

**Issue by marek-grzymala** [AleksandrHovhannisyan/aleksandrhovhannisyan.com#148]
copyCode.js:5 Uncaught TypeError: Cannot read properties of undefined (reading 'innerText')

**Comment by AleksandrHovhannisyan** [comment]
Hi, is this an error you encountered on my website, or is it related to the article I wrote on this topic? If it's the latter, I recommend posting in the corresponding comments thread here along with additional details: https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/issues/35
