### ISSUE TITLE
Feature Request: Front Matter Format For Local Image

### ISSUE THREAD

**Issue by inetbiz** [AleksandrHovhannisyan/aleksandrhovhannisyan.com#158]
**Feature description**
Could you update your readme to example how you'd add a local image to the frontmatter of a blog post? I tried for hours! I kept getting errors.

**Ideas you have for implementing this (optional)**

**Additional context (if applicable)**

**Comment by AleksandrHovhannisyan** [comment]
Thanks for the feedback. Since this repo isn't meant to be reused, it wouldn't make sense for me to explain this in the readme.
