### ISSUE TITLE
Lamp icon use?

### ISSUE THREAD

**Issue by simplerethink** [AleksandrHovhannisyan/aleksandrhovhannisyan.com#176]
Any chance I could use your css lamp icon (in the navbar) on my site? It's similar to something I was going to create myself.

**Comment by AleksandrHovhannisyan** [comment]
Hi! I don't own the _concept_ of using a lamp icon for a theme toggle, so you're obviously free to create one yourself. The only thing I'd take issue with is if you were to copy-paste my code for it. Thanks for checking!

**Comment by AleksandrHovhannisyan** [comment]
Feel free to reopen if you have more questions
