### ISSUE TITLE
RSS feed issue

### ISSUE THREAD

**Issue by muratcorlu** [AleksandrHovhannisyan/aleksandrhovhannisyan.com#181]
I want to inform you that, your RSS feed is being broken in some non-regular cycles. Last time a few hours ago, I got around 80 of your old posts as new posts in my rss reader (I use News Explorer app)

<img width="479" alt="image" src="https://user-images.githubusercontent.com/127687/216655914-bd24d73f-6036-49de-9eea-8a4b7844fd91.png">

I assume something happens about dates of IDs of the feed items but couldn't dive into details.

For your information...

**Comment by AleksandrHovhannisyan** [comment]
Oh, yikes, that's no good! Thanks for flagging—I'll take a look.

**Comment by AleksandrHovhannisyan** [comment]
Out of curiosity, do you recall if you noticed this issue when you first subscribed or if it's a recent regression? I wonder if it could be a bug with the feed app itself. My latest build was a few days ago, and the publication dates are showing correctly.

**Comment by muratcorlu** [comment]
I had this issue maybe 2 or 3 times in last few months. First time I thought you just updated your feed structure or something that caused loosing track of previous items. 😊 

Indeed, it can be related with the app itself especially no one  noticed a problem like this. But I follow more than 100 feeds for more than 1 year and this problem only happens with  your blog.

I’m not sure about RSS internals but W3C RSS validator highlight some issues in the feed: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.aleksandrhovhannisyan.com%2Ffeed.xml 

I don’t know if those can cause that kind of issues in some *sensitive* feed readers 😊

**Comment by AleksandrHovhannisyan** [comment]
Ah, thanks for sharing those validation results! Looks like I'm using UTC strings when I should be using ISO/RFC3339 strings (this regressed in c03e2f1 about six months ago). Will push up a fix and hopefully that takes care of things, although I don't recall why I originally switched to UTC strings...

**Comment by AleksandrHovhannisyan** [comment]
@muratcorlu Validator is passing, so fingers crossed that it's fixed! When you get a chance, could you please test and let me know? I don't have a Mac to test on.

**Comment by muratcorlu** [comment]
Great! I don't see any problems for now. If I notice something, I'll inform you.
