### ISSUE TITLE
How to Set up Create React App with TypeScript, Ant Design, LESS, CSS Modules, and ESLint

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [AleksandrHovhannisyan/aleksandrhovhannisyan.com#30]

**Comment by IanSaucy** [comment]
Hey great post! As a heads up your `config-overrides.js` needs and update due to the breaking change introduced in `customize-cra` mentioned here https://github.com/arackaf/customize-cra/issues/253

**Comment by AleksandrHovhannisyan** [comment]
@IanSaucy Thanks for letting me know! I just tested this out locally and you're right. I've updated the blog post with the new less loader configuration object.

**Comment by vsosinga** [comment]
Thanks for the great and up-to-date guide!

**Comment by glinkot** [comment]
Really useful, I've found ant styling to be much better than material UI (so far!) but the LESS thing had me scratching my head.  Every step was perfect, thanks so much!

**Comment by muco-rolle** [comment]
Thanks for this great work

**Comment by 4imble** [comment]
Just starting out with react (coming from years of using Aurelia). This was very helpful to get me up and running with the essentials. Many thanks!

**Comment by elend80** [comment]
Thank you very much. It was very useful.

**Comment by jihainan** [comment]
very useful !!!

**Comment by Nelsonfrank** [comment]
Thank you for the useful post, it is really helpful

**Comment by Nelsonfrank** [comment]
How about performance of this implementation?!..

**Comment by AleksandrHovhannisyan** [comment]
@Nelsonfrank Glad you found it helpful!

I'm not aware of any performance issues. At the end of the day, it's React, so make of that what you will 😄

**Comment by 4imble** [comment]
Did you remove this article? I couldn't find it anywhere. Maybe I'm being blind, but would be a shame if you had.

**Comment by AleksandrHovhannisyan** [comment]
@4imble Technically, yes, but it's still published (I just don't link to it anywhere and I've taken it off Google): https://www.aleksandrhovhannisyan.com/blog/archived/how-to-set-up-react-typescript-ant-design-less-css-modules-and-eslint/.

**Comment by glinkot** [comment]
@AleksandrHovhannisyan Hi!  I just thought I'd say, this guide was super useful and I'd come to see if there was an updated version.  I see the link just above is now removed, which is a shame.  Lucky I copy pasted a proper copy at the time - if you get a chance to reinstate it or do an updated one, I'm sure lots of people would benefit.  Thanks again!  It's how I set my projects up now.
