### ISSUE TITLE
Multiple Modals on One Page Using HTML, CSS, and JavaScript

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [AleksandrHovhannisyan/aleksandrhovhannisyan.com#31]

**Comment by baerlein** [comment]
Thank you for a great tutorial!

How do you control the style of the second modal? (in stacked modals).
Right now it looks a bit smaller than the first one but I don't understand why.

**Comment by AleksandrHovhannisyan** [comment]
@baerlein  Sure! The only reason the stacked modal is so small is because its size depends on the amount of content it has. And since it doesn't have a lot of content, the modal appears very small. You can change the dimensions of your modal windows as needed using `width` and `height` properties, just as you would for any other element. Here's an example:

![image](https://user-images.githubusercontent.com/19352442/92619149-25fffd00-f28f-11ea-821c-91cd6b29182d.png)

I would just be careful with overflows on mobile if you decide to use hard-coded pixel values like I did in that example. You can instead use percentages (e.g., `width: 90%`). But that'll look quite big on desktop. So you can probably set some media query breakpoints to get around this.

Also, keep in mind that each `.modal-wrapper` is a flex container, so you can also use the `flex-basis` property on `.modal-window` to regulate its width. That's just an alternative approach.

I hope that helps!

**Comment by baerlein** [comment]
That's very helpful, thanks!
