### ISSUE TITLE
Can't write down any <p> elements </p>

### ISSUE THREAD

**Issue by MyHtmlCoding** [AleksandrHovhannisyan/aleksandrhovhannisyan.com#65]
I used the same code as on the website, but I have no idea where to insert my lines of paragraph cause if I type it under the header, It won't appear. Please help. I want to make a website... 

Here is the HTML. 
Sorry, I really don't know why it doesn't show the full HTML code. I typed <p> hello </p> at the line </header>. I used the same code from the website, btw. Also, the paragraph element doesn't show on github. Dude.
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Voidify</title>
    <link rel="stylesheet" type="text/css" href="stylevoidify.css">
</head>
<body>
    <header id="navbar">
        <nav class="navbar-container container">
          <a href="/" class="home-link">
            <div class="navbar-logo"></div>
            Voidify
          </a>
          <button type="button" class="navbar-toggle" aria-label="Open navigation menu">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <div class="navbar-menu">
            <ul class="navbar-links">
              <li class="navbar-item"><a class="navbar-link" href="/about">About</a></li>
              <li class="navbar-item"><a class="navbar-link" href="/blog">Blog</a></li>
              <li class="navbar-item"><a class="navbar-link" href="/careers">Careers</a></li>
              <li class="navbar-item"><a class="navbar-link" href="/contact">Contact</a></li>
            </ul>
          </div>
        </nav>
    </header>
    _**<p> Hello </p>**_
    <script src="voidifyscripts.js"></script>
</body>
</html>

**Comment by AleksandrHovhannisyan** [comment]
Hi,

I just noticed this issue. Could you please clarify what this is referring to? Is it a particular tutorial?

Thanks!

**Comment by AleksandrHovhannisyan** [comment]
I'm closing this issue for now, but if you'd like me to reopen it, please respond and clarify what it's about. Thank you!
