### ISSUE TITLE
Bug Report: Update to Formspree endpoint creation

### ISSUE THREAD

**Issue by daviddarnes** [AleksandrHovhannisyan/aleksandrhovhannisyan.com#67]
## Summary
Hey Aleksandr! I stumbled upon [your Formspree tutorial](https://www.aleksandrhovhannisyan.com/blog/add-a-contact-form-to-your-website-for-free-with-formspree/) and found it to be very helpful for anyone else using Formspree for their website forms. I just wanted to let you know that Formspree now doesn't require exposing your email to create forms, if you sign up for a free account at formspree.io you can generate a custom endpoint and use that instead. There's more info here on the help docs: https://help.formspree.io/hc/en-us/articles/360056076314-Phasing-out-legacy-forms-email-URLs

**Steps to Reproduce**
1. Navigate to the following article and follow the steps in the tutorial https://www.aleksandrhovhannisyan.com/blog/add-a-contact-form-to-your-website-for-free-with-formspree/

**Expected Behavior**
That a custom endpoint ID is created rather than an exposed email address

**Desktop (please complete the following information):**
 - All

**Smartphone (please complete the following information):**
 - All

**Additional context (if applicable)**
If you need any help with updating this article let me know! Happy to send over a PR into the article itself 👍🏻

**Comment by AleksandrHovhannisyan** [comment]
Hey, thanks for writing in! Sorry that I missed this. The post actually mentions this at the top, but I couldn't be bothered to rewrite the post.

**Comment by daviddarnes** [comment]
@AleksandrHovhannisyan ah great, thanks!
