### ISSUE TITLE
Feature Request/Suggestion: RSS

### ISSUE THREAD

**Issue by kazlauskis** [AleksandrHovhannisyan/aleksandrhovhannisyan.com#69]
Heya, I'm using Feedly and I have found your blog to be interesting. Does it have some RSS feed I could tap into? Thanks

**Comment by AleksandrHovhannisyan** [comment]
@kazlauskis Hey! Sorry  for the delay in getting back to you; I didn't get a notification for some reason. My blog does have an RSS feed, but I just don't link to it on my site (I should probably do that, lol). You can find it here: https://www.aleksandrhovhannisyan.com/feed.xml.

**Comment by kazlauskis** [comment]
Ah, cheers!
