### ISSUE TITLE
Feature Request/Suggestion: Lamp Blog for Light / Dark Mode

### ISSUE THREAD

**Issue by gojimmypi** [AleksandrHovhannisyan/aleksandrhovhannisyan.com#72]
**Feature description**

Create a walk-through blog post on how to change the light / dark color theme with the lamp icon, specifically how you implemented [this](https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/blob/78efb68997389421a980ea1f937b98abe2f8f57d/src/_includes/navbar.html#L27):

![image](https://user-images.githubusercontent.com/13059545/113515017-c6b55300-9526-11eb-8985-47a1edaa4bc7.png)

**Ideas you have for implementing this (optional)**

Similar to your other informative and well written blog posts, it would be great to see how you implemented the style toggle. 

Thanks for sharing

**Comment by AleksandrHovhannisyan** [comment]
@gojimmypi Hey, thanks for the feedback! I don't intend to publish a tutorial on this since I meant for it to be a fun/unique thing to differentiate my site from other blogs.

**Comment by gojimmypi** [comment]
Hello @AleksandrHovhannisyan and yes, I completely understand that you won't be creating a blog on this topic. It is however, too cool of a feature and I did implement something clearly based on your blog as a starting point on [my blog](https://gojimmypi.github.io/gridster-jekyll-theme/dark-mode/)  as I really wanted a dark mode toggle feature just like yours. I hope you don't mind? Although I adapted my own code and functionality, the little lamp is clearly a copy of yours. 

I just read your [README as it was at the time](https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/blob/5b1b5e89b66c6408f51f7eff0be3a58017ef9dd9/README.md) and understand if perhaps you also prefer I not use your lamp icon? I think when I first read that, I was assuming the _content_ of your blog was restricted: the text of the articles and awesome details of how you've implemented things are of course not to be shared. Please advise if I can use your little lamp icon, as I would like to respect your work & preferred scope of sharing,

**Comment by AleksandrHovhannisyan** [comment]
@gojimmypi Thanks a bunch for crediting me! I also really appreciate you asking me if this is okay. Some other people have straight up copy-pasted stuff in the past without giving me any credit, lol 😄

Yep, I'd appreciate if you could remove this lamp. (But of course, I don't mind if you draw _another_ lamp, or a lightbulb, etc.—I don't own the _idea_ of a lamp for a dark mode toggle).

I'll probably update my README to clarify the wording, too. Thank you!

**Comment by gojimmypi** [comment]
heya @AleksandrHovhannisyan - my apologies for using the lamp icon without your permission, as I had misunderstood. I've removed it from my [new blog](https://gojimmypi.github.io/gridster-jekyll-theme/). I'm now using sun/moon icons for the the dark mode / light mode toggle.

You may have noticed that work has been and is still just a preview, as I never actually pushed it to my [new blog home](https://gojimmypi.github.io/) yet. Clearly it still needs a lot of work. :sweat_smile:

**Comment by AleksandrHovhannisyan** [comment]
@gojimmypi No worries at all! And best of luck with the new blog 😄
